# -*- coding: utf-8 -*-
"""Object Detection for Sign language

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rKovchcInJ02xdnYBKP-F-bp24FNV9R0

<a href="https://colab.research.google.com/github/khanhlvg/tflite_raspberry_pi/blob/main/object_detection/Train_custom_model_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

!pip install -q tflite-model-maker
!pip install -q tflite-support

import numpy as np
import os

from tflite_model_maker.config import ExportFormat, QuantizationConfig
from tflite_model_maker import model_spec
from tflite_model_maker import object_detector

from tflite_support import metadata

import tensorflow as tf
assert tf.__version__.startswith('2')

tf.get_logger().setLevel('ERROR')
from absl import logging
logging.set_verbosity(logging.ERROR)

!wget https://iot.loopweb.lk/android_figurine.zip
!unzip -q android_figurine.zip

train_data = object_detector.DataLoader.from_pascal_voc(
    'android_figurine/train',
    'android_figurine/train',
    ['hello', 'yes','no','thanks']
)

val_data = object_detector.DataLoader.from_pascal_voc(
    'android_figurine/validate',
    'android_figurine/validate',
    ['hello', 'yes','no','thanks']
)

spec = model_spec.get('efficientdet_lite0')

model = object_detector.create(train_data, model_spec=spec, batch_size=4, train_whole_model=True, epochs=5000, validation_data=val_data)

model.evaluate(val_data)

model.export(export_dir='.', tflite_filename='android.tflite')

model.evaluate_tflite('android.tflite', val_data)

# Download the TFLite model to your local computer.
from google.colab import files
files.download('android.tflite')